endpoint: wss://sys.ibp.network/coretime-kusama
mock-signature-host: true
db: ./db.sqlite

import-storage:
  System:
    Account:
      - - - 5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY
        - providers: 1
          data:
            free: 1000000000000000
  Broker:
    Configuration:
      advance_notice: 20
      interlude_length: 10
      leadin_length: 10
      ideal_bulk_proportion: 0
      limit_cores_offered: 50
      region_length: 30
      renewal_bump: 10
      contribution_timeout: 5
    SaleInfo:
      saleStart: 2831089
      leadinLength: 50400
      endPrice: 93489341
      regionBegin: 361368
      regionEnd: 366408
      idealCoresSold: 38
      coresOffered: 94
      firstCore: 6
      selloutPrice: 962940212
      coresSold: 42
