endpoint: ws://127.0.0.1:9955
mock-signature-host: true
db: ./db.sqlite

import-storage:
  System:
    Account:
      - - - 5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY
        - providers: 1
          data:
            free: 1000000000000000
  Regions:
    Regions:
      [
        [
          [{ core: 0, begin: 366408, mask: "0xffffffffffffffffffff" }],
          {
            owner: 5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY,
            locked: true,
            record:
              {
                Available:
                  {
                    end: 371448,
                    owner: "5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY",
                    paid: null,
                  },
              },
          },
        ],
        [
          [{ core: 1, begin: 366408, mask: "0xffffffffffffffffffff" }],
          {
            owner: 5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY,
            locked: true,
            record:
              {
                Available:
                  {
                    end: 371448,
                    owner: "5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY",
                    paid: null,
                  },
              },
          },
        ],
      ]
  Market:
    Listings: [
        [
          [{ core: 0, begin: 366408, mask: "0xffffffffffffffffffff" }],
          {
            seller: 5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY,
            timeslice_price: 1000000000, # 0.001 KSM / timeslice
            sale_recipient: 5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY,
          },
        ],
        [
          [{ core: 1, begin: 366408, mask: "0xffffffffffffffffffff" }],
          {
            seller: 5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY,
            timeslice_price: 15000000000, # 0.0015 KSM / timeslice
            sale_recipient: 5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY,
          },
        ],
      ]
