[settings]
timeout = 1000

[relaychain]
chain = "kusama-local"
chain_spec_command = "chain-spec-generator {% raw %} {{chainName}} {% endraw %}"
command = "polkadot"

  [[relaychain.nodes]]
  name = "kusama-validator01"
  validator = true

  [[relaychain.nodes]]
  name = "kusama-validator02"
  validator = true

[[parachains]]
id = 1005
chain = "coretime-kusama-local"
chain_spec_command = "chain-spec-generator {% raw %} {{chainName}} {% endraw %}"
addToGenesis = false

  [parachains.collator]
  name = "coretime-collator01"
  command = "polkadot-parachain"
  args = [ "--log=xcm=trace" ]

[[parachains]]
id = 2000
chain = "regionx-kusama-dev"
addToGenesis = false

  [parachains.collator]
  name = "regionx-collator01"
  command = "regionx-node"
  args = [ "--enable-offchain-indexing true --log=xcm=trace,regions=trace" ]
