name: Basic

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  pull_request:
    branches:
    - main
  push:
    branches:
    - main
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  fmt:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4
    - uses: Swatinem/rust-cache@v2
    - uses: ./.github/actions/setup

    - name: Cancel Previous Workflow Runs
      uses: styfle/cancel-workflow-action

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Cancel Previous Runs
      uses: styfle/cancel-workflow-action@0.9.1
      with:
        access_token: ${{ github.token }}
        workflow_id: ${{ github.workflow }}
    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.GH_TOKEN }}

    - name: Use Git CLI for Cargo
      run: echo "CARGO_NET_GIT_FETCH_WITH_CLI=true" >> $GITHUB_ENV

    - name: Cargo fmt
      run: cargo +nightly fmt --all -- --check

  lint-and-check:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4
    - uses: Swatinem/rust-cache@v2
    - uses: ./.github/actions/setup

    - name: Cancel Previous Workflow Runs
      uses: styfle/cancel-workflow-action

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.GH_TOKEN }}

    - name: Use Git CLI for Cargo
      run: echo "CARGO_NET_GIT_FETCH_WITH_CLI=true" >> $GITHUB_ENV

    - name: Cargo clippy
      run: cargo +nightly clippy -- -D warnings
  
    - name: Check Code
      run: cargo check

  check-dependencies:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/setup

    - name: Cancel Previous Workflow Runs
      uses: styfle/cancel-workflow-action

    - name: Install psvm
      run: |
        cargo install --git https://github.com/paritytech/psvm psvm

    - name: Check Dependency Versions
      run: |
        chmod +x ./scripts/check-dependency-versions.sh
        ./scripts/check-dependency-versions.sh 

  code_coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - uses: ./.github/actions/setup

      - name: Cancel Previous Workflow Runs
        uses: styfle/cancel-workflow-action

      - name: Checkout the source code
        uses: actions/checkout@v3

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.GH_TOKEN }}

      - name: Run cargo-tarpaulin
        uses: actions-rs/tarpaulin@v0.1
        with:
          version: "0.21.0"

      - name: Upload to codecov.io
        uses: codecov/codecov-action@v3.1.0
        with:
          token: ${{secrets.CODECOV_TOKEN}}

      - name: Archive code coverage results
        uses: actions/upload-artifact@v3.1.0
        with:
          name: code-coverage-report
          path: cobertura.xml
